project_id = "lhjdtonlgqtfjryjkppp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions.chat-assistant]
verify_jwt = false

[functions.weather-data]
verify_jwt = false

[functions.market-data]
verify_jwt = false
