project_id = "lhjdtonlgqtfjryjkppp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions.chat-assistant]
verify_jwt = false

[functions.weather-data]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.analyze-image]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-image/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analyze-image/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analyze-image/*.html" ]
